### ISSUE TITLE
Show Photo from DG.EF2

### ISSUE THREAD

**Issue by KevinMeyerZ** [ZeroPass/dmrtd#12]
how do i get the photo from nfc to show up ?

**Comment by smlu** [comment]
The EF.DG2 file has to be parsed in order to get the raw image data. The [develop](https://github.com/ZeroPass/dmrtd/tree/develop) branch has implemented parsing of this file, see [efdg2.dart](https://github.com/ZeroPass/dmrtd/blob/develop/lib/src/lds/df1/efdg2.dart). The image is usually encoded in JPEG-2000 format which is not currently supported by the flutter and you will have to provide your own conversion method in order to display passport image in flutter.

See also #9

**Comment by KevinMeyerZ** [comment]
thanks a lot, it works

**Comment by zamirszn** [comment]
> thanks a lot, it works
> 

Hello, how were you able to extract the image
