### ISSUE TITLE
Support for PACE 2.0 authentication using CAN

### ISSUE THREAD

**Issue by urbanjagodic** [ZeroPass/dmrtd#4]
Hi,

is there any further progress for supporting PACE authentication with CAN based access key?
Currently there is only BAC, which is slowly becoming deprecated and superseded by PACE.

**Comment by smlu** [comment]
Hey!
Yes, the plan is to eventually support PACE session establishing protocol in the near future.

**Comment by gavinkilbride** [comment]
Hi, 
First off, thanks for building such a great library. Secondly, is there still active development happening? 
in January 2018, documents that implement PACE were no longer required by the ICAO standard to implement BAC for backwards compatibility. Since 2020, some countries have dropped support for BAC in newly issued documents, requiring PACE to get access to the content on the chip, as more and more time goes by there are going to be fewer and fewer BAC passports out there. I'm not sure how many countries are dropping support for BAC but it would be awesome to have support for PACE so that it doesn't become an issue. If you're looking for help I might be able to find someone to assist.

**Comment by lukapercic** [comment]
@gavinkilbride we are actively looking for an opportunity to build it out, you don't need to convince us of PACE necessity :)

I send you an email.
